import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
            <div className="bg-indigo-700 p-6 w-full">
                <div className="flex md:flex-row flex-col justify-between md:items-center gap-2">
                    <h1 className='font-bold text-2xl'>CuyAnimeList</h1>
                    <input
                        placeholder="cari anime..."
                        className="p-2 rounded"
                    />
                </div>
            </div>
            {children}
            </body>
        </html>
    )
}
